# Generated by Django 4.2.11 on 2024-04-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsession',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
