# Generated by Django 4.2.11 on 2024-04-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0002_alter_gymsession_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymsession',
            options={'ordering': ('-date',), 'verbose_name': 'Gym Session', 'verbose_name_plural': 'Gym Sessions'},
        ),
        migrations.AlterModelOptions(
            name='gymsessionimage',
            options={'ordering': ('-upload_date',), 'verbose_name': 'Gym Session Image', 'verbose_name_plural': 'Gym Session Images'},
        ),
    ]
